texte_intro:
	dc.b	"                                ",$FE
	dc.b	"                                ",$FE
	dc.b	"Hey salut "
pseudo:
	ds.b	12
	dc.b	"         ",$FE
	dc.b	"                                ",$FF
defile:
	dc.b	"Ici Zisquier, je suis prisonnier",$FE
	dc.b	"… l'int‚rieur de ce programme !!",$FE
	dc.b	"                                ",$FE
	dc.b	"J'ai ‚t‚ comme aspir‚ par mon   ",$FE
	dc.b	"Ultra Satan aprŠs avoir assembl‚",$FE
	dc.b    "mon code source !!!             ",$FE
	dc.b	"                                ",$FE
	dc.b	"R‚sultat je ne peux pas ˆtre l…,",$FE
	dc.b	"enfin si je suis l… ... mais pas",$fe
	dc.b	"vraiment.                       ",$fe
	dc.b	"                                ",$fe
	dc.b 	"D‚sol‚ donc Shaoth, Papy CPC et ",$fe
	dc.b	"tous ceux  du GEMTOS 2022  dont ",$fe
	dc.b	"j'ai fait connaissance, mais ma ",$fe
	dc.b	"reconvertion professionnelle me ",$fe
	dc.b	"prends  beaucoup trop  de temps ",$fe
	dc.b	"pour pouvoir ˆtre pr‚sent cette ",$fe
	dc.b	"ann‚e.                          ",$fe
	dc.b	"                                ",$fe
	dc.b	"Mais c'est promis, je viendrai  ",$fe
	dc.b	"pour le prochain GEMTOS !       ",$fe
	dc.b	"                                ",$fe
	dc.b	"En ce moment je bosse sur un jeu",$fe
	dc.b	"de type shmup sur Amstrad GX4000",$fe
	dc.b 	"sur le theme de GOLDORAK. Donc  ",$fe
	dc.b	"une fois fini  je remet  le nez ",$fe
	dc.b	"dans ce code obscure du 68000 :)",$fe
	dc.b	"                                ",$fe
	dc.b	"En attendant  vous pouvez voir  ",$fe
	dc.b	"les progrŠs que j'ai fait cette ",$fe
	dc.b	"ann‚e :)                        ",$fe
	dc.b	"C'est trŠs exp‚rientale, je test",$fe
	dc.b	"beaucoup de choses donc il y a  ",$fe
	dc.b	"beaucoup de bug ‚galement !     ",$fe
	dc.b	"donc merci … toi, "
pseudo2:	
	ds.b	12
        dc.b	"  ",$fe
	dc.b	"                                ",$fe
	dc.b	"Pour ton indulgence ! :)        ",$fe
	dc.b	"Bon GEMTOS 2023 !               ",$fe
	dc.b	"                                ",$fe
	dc.b	"                       Zisquier ",$fe
	dc.b	"                                ",$ff
