texte_intro:
	dc.b	"                                ",$FE
	dc.b	"                                ",$FE
	dc.b	"Hey salut "
pseudo:
	ds.b	12
	dc.b	"         ",$FE
	dc.b	"                                ",$FF
defile:
	dc.b	"Dans  le  chapitre  pr‚c‚dant,  ",$FE
	dc.b	"sur AMSTRAD 6128+,  la culotte  ",$FE
	dc.b	"de Zelda … ‚t‚ retrouv‚e et Link",$FE
	dc.b	"a pu decrouvrir le coupable ... ",$FE
	dc.b	"Mario ...  oui,  encore  lui  !!",$FE
	dc.b	"Ce fourbe moustachu en salopette",$FE
	dc.b	"s'‚tait  d‚guis‚  en  princesse ",$FE
	dc.b	"pour tromper son monde.         ",$FE
	dc.b	"                                ",$fe
	dc.b	"Malheureusement pour lui, Link, ",$fe
	dc.b	"obsed‚   par   la   princesse,  ",$fe
	dc.b 	"n'avait  pu  contenir  sa  rage ",$fe
	dc.b	"(oui, toutes ces emmerdes pour  ",$fe
	dc.b	"retrouver une culotte, ‡a gonfle",$fe
	dc.b	"un peu)                         ",$fe
	dc.b	"Zelda s'en prit plein le * * *. ",$fe
	dc.b	".... enfin Mario en fait ...    ",$fe
	dc.b	"                                ",$fe
	dc.b	"                                ",$fe
	dc.b	"Ce que vous ne savez pas ...    ",$fe
	dc.b	"C'est que suite … cette histoire",$fe
	dc.b	"Mario, furax (Link y avait ‚t‚ …",$fe
	dc.b 	"sec ...) alla trouver Zelda et  ",$fe
	dc.b	"lui arracha  les membres un par ",$fe
	dc.b	"un .... un vrai 'serial killer'!",$fe
	dc.b	"on ne retrouva que la main ...  ",$fe
	dc.b	"Le reste du corp fut dispers‚ au",$fe
	dc.b	"royaume d'HYRULE ....           ",$fe
	dc.b	"                                ",$fe
	dc.b	"(snif !)                        ",$fe
	dc.b	"                                ",$fe
	dc.b	"Mais toi !                      ",$fe
	dc.b	"... oui ... TOI,  "
pseudo2:	
	ds.b	12
        dc.b	"  ",$fe
	dc.b	"                                ",$fe
	dc.b	"Tu vas devoir retrouver les     ",$fe
	dc.b	"morceaux de la princesse et la  ",$fe
	dc.b	"reconstituer !                  ",$FE
	dc.b	"                                ",$fe
	dc.b	"Allez, GO !                     ",$fe
	dc.b	"                                ",$fe
	dc.b	"                       Zisquier ",$fe
	dc.b	"                                ",$ff
